routes/web.php
<?php

use App\Http\Controllers\{
    AuthController,
    CommonController,
    GroupController,
    UserController
};
use Illuminate\Support\Facades\{Route};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
})->middleware(['auth', 'checkLogin']);

Route::get('/login', [AuthController::class, 'login'])->name('login');
Route::post('/handleLogin', [AuthController::class, 'handleLogin'])->name('handleLogin');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::get('/error', function () {
    return view('common.error');
})->middleware(['checkLogin', 'no-cache'])->name('error');

Route::prefix('common')->as('common.')->group(function () {
    Route::get('resetSearch', [CommonController::class, 'resetSearch'])->name('resetSearch');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'checkLogin']], function () {

    Route::group(['prefix' => 'user'], function () {
        // user list search
        Route::get('/', [UserController::class, 'userList'])->name('userList');
        Route::post('/export',[UserController::class, 'exportCSV'])->middleware(['checkPermissions','check-director'])->name('userExport');
        Route::post('/clear',[UserController::class, 'clearSearch'])->name('clear');

        // add
        Route::get('/add-edit-delete', [UserController::class, 'add'])->middleware(['checkPermissions','check-director'])->name('add');
        Route::post('/add-edit-delete', [UserController::class, 'handleAdd'])->middleware(['checkPermissions','check-director'])->name('handleAdd');

        // edit delele
        Route::get('/add-edit-delete/{id}', [UserController::class, 'edit'])->middleware(['checkPermissions'])->name('edit');
        Route::put('/add-edit-delete/{id}', [UserController::class, 'handleEdit'])->middleware(['checkPermissions','check-director'])->name('handleEdit');
       
        Route::get('/delete/{id}', [UserController::class, 'handleDelete'])->middleware(['checkPermissions'])->name('handleDelete');
        Route::get('/cancle', [UserController::class, 'cancle']);
        // route check email exist
        Route::post('/checkEmail', [UserController::class, 'CheckExistEmail'])->name('checkEmail');

    });

    Route::group(['prefix' => 'group', 'middleware' => ['check-director']], function () {
        Route::get('/', [GroupController::class, 'groupList'])->name('groupList');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\ObservantTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use ObservantTrait;
    use HasFactory;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    protected $table = 'user';

    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'email',
        'password',
        'name',
        'group_id',
        'position_id',
        'started_date',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
    ];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [
        'started_date',
        'created_date',
        'updated_date',
        'deleted_date',
    ];

    protected $casts = [
        'started_date' => 'date',
        'created_date' => 'date',
        'updated_date' => 'date',
        'deleted_date' => 'date',
    ];

    public function group() {
        return $this->belongsTo(Group::class, 'group_id');
    }

    public function getPosition()
    {
        $positions = [
            0 => 'Director',
            1 => 'Group Leader',
            2 => 'Leader',
            3 => 'Member',
        ];
    
        return $positions[$this->position_id] ?? '';
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\SearchUsersRequest;
use App\Http\Requests\{AddUserRequest, EditUserRequest};
use App\Libs\ConfigUtil;
use App\Models\User;
use App\Repositories\{GroupRepository, UserRepository};
use App\Services\UserService;
use Carbon\Carbon;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{Auth, Cookie};

class UserController extends Controller
{
    protected UserRepository $userRepository;

    protected GroupRepository $groupRepository;

    protected UserService $userService;

    public function __construct(UserRepository $userRepository, UserService $userService, GroupRepository $groupRepository) {
        $this->userRepository = $userRepository;
        $this->userService = $userService;
        $this->groupRepository = $groupRepository;
    }

    public function userList(SearchUsersRequest $request) {
        // check user logged
        if (! Auth::check() || Auth::user()->deleted_date != null) {
            return redirect()->route('login');
        }

        // get params search
        $searchParams = $request->only(['name', 'started_date_from', 'started_date_to','page']);

        if (count(array_filter($searchParams)) === 0) {
            $searchParams = [
                'name' => null,
                'started_date_from' => null,
                'started_date_to' => null,
            ];
        }

        session()->forget('user.search');
        session()->put('user.search', $searchParams);

        // handle search
        return $this->handlesearch($request);
    }

    public function handlesearch(SearchUsersRequest $request) {
        $searchParams = session()->get('user.search');
        $isSearch = session()->get('user.isSearch');
        $messageNotFound = '';
        if (count($request->all()) > 0) {
            $isSearch = true;
            session()->put('user.isSearch', $isSearch);
        }

        // If not search ( first time visit page) show view with empty value
        if (! $isSearch) {
            $users = [];
            $searchParams = [];

            return view('screens.user.list', compact('users', 'searchParams', 'messageNotFound'));
        }

        // search data with search params
        $users = $this->userService->search($searchParams);
        $users = $this->pagination($users);

        // return view with users value and searchParams
        if (count($users) == 0) {
            $messageNotFound = 'No User Found';
        }

        return view('screens.user.list', compact('users', 'searchParams', 'messageNotFound'));
    }

    public function exportCSV() {
        $exportParams = session()->get('user.search');
        if ($exportParams == null || count($exportParams) == 0) {
            return back();
        }

        $users = $this->userService->exportCSV($exportParams);

        if ($users == null || count($users) == 0) {
            return back();
        }

        $fileName = 'list_user_' . Carbon::now('Asia/Ho_Chi_Minh')->format('YmdHis') . '.csv';

        $filePath = storage_path('app/' . $fileName);
        $file = fopen($filePath, 'w');

        fputcsv($file, ['"ID"', '"User Name"', '"Email"', '"Group ID"', '"Group Name"', '"Started Date"', '"Position"', '"Created Date"', '"Updated Date"']);
        foreach ($users as $row) {
            fputcsv($file, $row);
        }
        fclose($file);

        $fileContents = file_get_contents($filePath);
        $fileContents = str_replace('""', '', $fileContents);
        file_put_contents($filePath, $fileContents);
        $response = response()->download($filePath, $fileName)->deleteFileAfterSend(true);
        $cookie = Cookie::make('exported', 'Ok', 1, null, null, false, false);
        $response->headers->setCookie($cookie);

        return $response;
    }

    public function clearSearch(Request $request) {
        try {
            $request->session()->forget('user.search');
            $request->session()->forget('user.isSearch');

            return response()->json([
                'hasError' => false,
            ]);
        } catch (Exception $e) {
            return response()->json([
                'hasError' => true,
            ]);
        }
    }

    public function add() {
        if (! Auth::check() || Auth::user()->deleted_date != null) {
            return redirect()->route('login');
        }

        $groups = $this->groupRepository->getListGroupForNewScreen();

        return view('screens.user.add-edit-delete', compact('groups'));
    }

    public function handleAdd(AddUserRequest $request) {
        $result = $this->userService->create($request);
        if ($result) {
            $searchParams = session()->get('user.search');
            $url = route('admin.userList', $searchParams); // Build the URL with search parameters

            return redirect($url)->with('success', ConfigUtil::getMessage('EBT096'));
        }

        return redirect()->back()->with('error', ConfigUtil::getMessage('EBT093'));
    }

    public function edit($id) {
        $user = $this->userRepository->findById($id);
        if ($user == null) {
            return redirect()->route('error');
        }

        $groups = $this->groupRepository->getListGroupForNewScreen();

        return view('screens.user.edit-delele', compact('groups', 'user'));
    }

    public function handleEdit(EditUserRequest $request) {
        $result = $this->userService->edit($request);
        if ($result) {
            $searchParams = session()->get('user.search');
            $url = route('admin.userList', $searchParams); // Build the URL with search parameters

            return redirect($url)->with('success', ConfigUtil::getMessage('EBT096'));
        }

        return redirect()->back()->with('error', ConfigUtil::getMessage('EBT093'));
    }

    public function handleDelete($id) {
        if ($id) {
            if ($id == Auth::user()->id) {
                return redirect()->route('admin.userList')
                    ->with('error', ConfigUtil::getMessage('EBT086'));
            }
            $userFound = $this->userRepository->findById($id);
            if ($userFound == null) {
                return route('error');
            }
            $userFound['deleted_date'] = Carbon::now()->toDateString();
            if ($userFound->save()) {
                $searchParams = session()->get('user.search');
                $url = route('admin.userList', $searchParams); // Build the URL with search parameters
                return redirect($url)->with('success', ConfigUtil::getMessage('EBT096'));
            }

            return redirect()->route('admin.userList')->with('error', ConfigUtil::getMessage('EBT093'));
        }
    }

    public function CheckExistEmail(Request $request) {
        if (isset($request->id)) {
            $user = $this->userRepository->getByEmail($request->email, $request->id);
        } else {
            $user = $this->userRepository->getByEmail($request->email);
        }

        if ($user->count()) {
            return response()->json([
                'duplicate' => true,
            ]);
        }

        return response()->json([
            'duplicate' => false,
        ]);
    }

    public function cancle(){
        $searchParams = session()->get('user.search');
                $url = route('admin.userList', $searchParams);
                return redirect($url);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * @var string
     */
    public $title;

    /**
     * Create a new component instance.
     */
    public function __construct($title = '')
    {
        $this->title = $title;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('layouts.app');
    }
}

resources/views/screens/user/add-edit-delete.blade.php
<x-app-layout title="UserAddEditDelete">
    @php
        $isDisable = false;
        if (in_array(Auth::user()->position_id, [1, 2, 3])) {
            $isDisable = true;
        }
    @endphp
    <div class="mb-sm-5 mx-sm-5 pt-5 col-sm-8">
        @if (session('error'))
            <div class="alert alert-danger text-white p-1">
                <span>{{ session('error') }}</span>
            </div>
        @endif
        {{-- FORM INSERT --}}
        <form action="{{ route('admin.handleAdd') }}" method="post" name="formAddUser" id="formAddUser">
            @csrf
            <div class="row pt-2">
                <div class="col-sm-6 ">
                    <div class="input-group" style="">
                        <label class=" col-6">
                            ID
                        </label>
                        <input type="hidden" name="id" value="">
                        <div class="col-sm-6">
                            <input type="text"  value="" class="form-control" disabled>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 ">
                    <x-forms.text-group label="User Name" name="name" :isRequired="true" :isDisabled="$isDisable" :value="old('name')" />
                </div>
            </div>
            <div class="row pt-2">
                <div class="col-sm-6 ">
                    <x-forms.text-group label="Email" id="email" name="email" :isRequired="true" :value="old('email')"
                        :isDisabled="$isDisable" />

                </div>
                <div class="col-sm-6">
                    <div class="input-group" style="">
                        <label class="input-required col-6">
                            Group
                        </label>
                        <div class="col-sm-6">
                            {{-- select2 --}}
                            <select class="form-select text-truncate border rounded-1 " name="group_id"  {{ $isDisable ? 'disabled' : '' }}>
                                @php
                                    $oldSelected = old('group_id') ?? '';
                                @endphp
                                @foreach ($groups as $group)
                                    <option value="{{ $group->id }}"@if ($oldSelected == $group->id) selected @endif>{{ $group->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row pt-2">
                <div class="col-sm-6 ">
                    <x-forms.text-group label="Started Date" id="started_date" name="started_date" :isRequired="true"
                        :isDisabled="$isDisable"  :value="old('started_date')"/>

                </div>
                <div class="col-sm-6">
                    <div class="input-group" style="">
                        <label class="input-required col-6">
                            Position
                        </label>
                        @php

                                $positions = [
                                    '0' => 'Director',
                                    '1' => 'Group Leader',
                                    '2' => 'Leader',
                                    '3' => 'Member',
                                ];
                                $selected = old('position_id') ?? '';

                            @endphp
                            <div class="col-sm-6">
                                <select class="form-select text-truncate border rounded-1" name="position_id" {{ $isDisable ? 'disabled' : '' }}>
                                    @foreach ($positions as $positionValue => $positionLabel)
                                        <option value="{{ $positionValue }}"{{ $positionValue == $selected ? 'selected' : '' }}>{{ $positionLabel }}</option>
                                    @endforeach
                                </select>
                            </div>
                    </div>
                </div>
            </div>
            <div class="row pt-2">
                <div class="col-sm-6 ">
                    <x-forms.text-group type="password" label="Password" id="password" name="password"
                        :isRequired="true" :value="old('password')" />

                </div>
                <div class="col-sm-6">
                    <x-forms.text-group type="password" label="Password Confirmation" id="repassword" name="repassword"
                        :isRequired="true" :value="old('repassword')" />
                </div>
            </div>

            <div class="row ">
                <div class="col-sm-9  d-flex justify-content-between">
                    <x-button.userlist label="Register" class="btn btn-secondary  text-truncate" type="submit"
                        style="width: 100px;" id="registerButton" name="registerButton"></x-button.userlist>

                    <x-button.userlist label="Update" class="btn btn-secondary d-none text-truncate" type="button"
                        style="width: 100px;" id="updateButton" name="updateButton"></x-button.userlist>

                    <x-button.userlist label="Delete" class="btn btn-secondary d-none  text-truncate" type="button"
                        style="width: 100px;" id="deleteButton"></x-button.userlist>

                        <a class="btn btn-secondary  text-truncate" href="/admin/user/cancle"
                                style="width: 100px;" id="Cancel">Cancel</a>
                </div>
            </div>

        </form>

    </div>

    @push('scripts')
        @vite(['resources/js/screens/user/userAdd.js'], 'build')
    @endpush

</x-app-layout>

resources/views/screens/user/list.blade.php
<x-app-layout title="User List">
    <div class="mb-sm-5 mx-sm-5 pt-5 col-sm-8">
        @if (session('error'))
            <div class="alert alert-danger text-white p-1">
                <span>{{ session('error') }}</span>
            </div>
        @endif
        @if (session('success'))
            <div class="alert alert-success text-white p-1">
                <span>{{ session('success') }}</span>
            </div>
        @endif
        <form action="{{ route('admin.userList') }}" method="get" name="formSearch" id="formSearch">
            <div class="row pt-2">
                <div class="col-sm-6 ">
                    <x-forms.text-group label="User Name" name="name" :value="$searchParams['name'] ?? old('name')" />
                </div>
            </div>
            <div class="row pt-2">
                <div class="col-sm-6 ">
                    <x-forms.text-group label="Started Date From" id="started_date_from" name="started_date_from"
                        :value="$searchParams['started_date_from'] ?? old('started_date_from')" />

                </div>
                <div class="col-sm-6">
                    <x-forms.text-group label="Started Date To" id="started_date_to" name="started_date_to"
                        :value="$searchParams['started_date_to'] ?? old('started_date_to')" />
                </div>
            </div>
            <div class="row d-flex">
                <div class="col-sm-5 gap-5 mr-md-4 d-sm-none d-md-block">
                </div>
                <div class="col-sm-6 gap-5 ml-md-3 ml-sm-0">
                    <x-button.userlist label="Clear" class="btn btn-secondary m-1 text-truncate" type="button"
                        style="width: 100px;" id="btnClear" name="btnClear"></x-button.userlist>
                    <x-button.userlist label="Search" class="btn btn-secondary m-1 text-truncate" style="width: 100px;"
                        id="btnSearch"></x-button.userlist>
                </div>
            </div>

        </form>
        @if (isset($users))
            @if (count($users) > 0)
                <div class="row d-flex mt-2 justify-content-center">
                    <div class="col-sm-4 d-md-none"></div>
                    <div class="col-sm-8 col-md-11 gap-5 ml-md-2 ml-sm-0">
                        {{ $users->links('common.pagination') }}
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-sm-10">
                        <table class="table table-bordered table-responsive-sm custom-table">
                            <thead>
                                <tr>
                                    <th class="fw-normal text-center">User Name</th>
                                    <th class="fw-normal text-center">Email</th>
                                    <th class="fw-normal text-center">Group Name</th>
                                    <th class="fw-normal text-center">Started Date</th>
                                    <th class="fw-normal text-center">Position</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <td>
                                            @if (Auth::user()->position_id == 0)
                                                <a href="{{ route('admin.edit', ['id' => $user->id]) }}"
                                                    class="text-decoration-underline "> {{ nl2br($user->name) }}
                                                </a>
                                            @else
                                                {{ nl2br($user->name) }}
                                            @endif
                                        </td>
                                        <td>
                                        
                                                {{ nl2br($user->email) }}
                                        
                                        </td>
                                        <td class="">{{ nl2br($user->group->name ?? '') }}</td>
                                        <td class="">
                                            {{ nl2br($user->started_date != null ? $user->started_date->format('d/m/Y') : '') }}
                                        </td>
                                        <td class="">{{ nl2br($user->getPosition()) }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>


                    </div>
                </div>
            @elseif ($messageNotFound != '')
                <div class="row mt-5 mx-1">
                    <div
                        class="col-sm-8 h-25 w-100 py-3 bg-danger border d-flex justify-content-center align-items-center">
                        <span class="mx-1 text-white">
                            {{ $messageNotFound }}
                        </span>
                    </div>
                </div>
            @endif

        @endif

        @if (Auth::user()->position_id == 0)
            <div class="row d-block">
                <div class="col">
                    <x-button.userlist label="New" class="btn btn-secondary m-1 text-truncate" type="button"
                        style="width: 100px;" id="btnNew" name="btnNew"></x-button.userlist>
                    @if (isset($users) && count($users) > 0)
                        <form action="{{ route('admin.userExport') }}" method="post" style="display: inline;">
                            @csrf
                            <x-button.userlist label="Export CSV" class="btn btn-secondary m-1 text-truncate"
                                style="width: 100px;" id="btnExport" name="btnExport"></x-button.userlist>
                        </form>
                    @endif
                </div>
            </div>
        @endif



    </div>

    @push('scripts')
        @vite(['resources/js/screens/user/userList.js'], 'build')
    @endpush
</x-app-layout>